[package]
name = "rusty-health-checker"
version = "0.1.0"
authors = ["Robert Crous <robert.crous21@gmail.com>"]
edition = "2018"

[dependencies]
structopt = "0.2.10"
reqwest = "0.9.17"
env_logger = "0.6.1"
log = "0.4.6"
